[phases.setup]
nixPkgs = ["php83", "php83Extensions.mysqli", "php83Extensions.curl", "php83Packages.composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -d extension=mysqli -S 0.0.0.0:${PORT:-8080} -t ."
